[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
]

[contracts]
proxy = ["src/proxy_contract/proxy.cairo"]
example = ["examples/template_example.cairo"]
main = ["src/chronos_oracle/main.cairo"]
